# Generated by Django 4.2.3 on 2023-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名字')),
                ('avatar', models.CharField(max_length=200, unique=True, verbose_name='头像')),
                ('signature', models.CharField(max_length=100, unique=True, verbose_name='签名')),
                ('announcement', models.CharField(max_length=200, unique=True, verbose_name='公告')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.CharField(max_length=300, verbose_name='封面图片'),
        ),
    ]
