# Generated by Django 4.2.3 on 2023-07-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_name_adminuser_aname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name_plural': '管理用户信息'},
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='t_AdminUser',
        ),
    ]
