# Generated by Django 4.2.3 on 2023-07-18 22:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_adminuser_options_alter_adminuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='关于'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='bilibili',
            field=models.CharField(default=123, max_length=200, unique=True, verbose_name='bilibili链接'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='github',
            field=models.CharField(default=123, max_length=200, unique=True, verbose_name='github链接'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminuser',
            name='steam',
            field=models.CharField(default=123, max_length=200, unique=True, verbose_name='steam链接'),
            preserve_default=False,
        ),
    ]
