# Generated by Django 4.2.3 on 2023-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_adminuser_about_adminuser_bilibili_adminuser_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='关于'),
        ),
    ]
