# Generated by Django 4.2.3 on 2023-07-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_adminuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='banner',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='横幅'),
            preserve_default=False,
        ),
    ]
